### ISSUE TITLE
What is wrong when, Failed to load skin? CSS File is loaded.

### ISSUE THREAD

**Issue by feldmarv** [privatejava/javafx-autocomplete-field#1]
Dez 09, 2015 9:59:35 AM javafx.scene.control.Control loadSkinClass
SCHWERWIEGEND: Failed to load skin 'np.com.ngopal.control.AutoFillTextBoxSkin' for control AutoFillTextBox[id=ortEditField, styleClass=autofill-text]
java.lang.ClassCastException
    at com.sun.javafx.collections.SortHelper.sort(SortHelper.java:50)
    at com.sun.javafx.collections.ObservableListWrapper.sort(ObservableListWrapper.java:216)
    at javafx.collections.FXCollections.sort(FXCollections.java:653)
    at np.com.ngopal.control.AutoFillTextBoxSkin.<init>(AutoFillTextBoxSkin.java:179)

**Comment by feldmarv** [comment]
I added an other jar, mentioned in this thread: http://stackoverflow.com/questions/28208364/javafx-autocomplete-field-1-0-jar-compatibility-issue

Link ot the jar: https://bitbucket.org/jugen/autofilltextbox/downloads

**Comment by privatejava** [comment]
I have changed to the Maven stucture and it would not give you now probem . Also updated the jar file now. I hope that problem will not come now. If you are using Java 1.7 then you will probably need  to use old builds. I would highly recomment to use new Java 1.8 and you should not put jfxrt.jar anywhere in your library as iti s already bundled in 1.8.
